name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Grant permission
        run: chmod +x gradlew
      - name: Build Ktor project
        run: ./gradlew installDist
      - name: Build Docker Image
        run: docker build -t jhoangamarra/fullmenudigital:latest
      - name: Push Docker image to Dockerhub
        run: docker push jhoangamarra/fullmenudigital:latest
